services:
  flask_app:
    build: .
    container_name: vulnerable_flask
    expose:
      - "5000"

  nginx_proxy:
    image: nginx:alpine
    container_name: vulnerable_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - flask_app
